alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: ackley_2d_gacem
  suffix: ns25_lay2x100_e10_b10_nr20_csp_off_fixed_sigma
  seed: 10
  ndim: 2
  goal_value: 3.5
  hidden_list: [100, 100]
  mode: le
  batch_size: 16
  nepochs: 10
  nsamples: 25
  n_init_samples: 50
  init_nepochs: 50
  cut_off: 10
  niter: 21
  lr: 5e-3
  beta: 10
  base_fn: normal
  nr_mix: 20
  only_positive: True
  full_training_last: True
  input_scale: 5.0
  eval_fn: ackley
  fixed_sigma: 0.05
  problem_type: csp