alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: styblinski_20d_gacem
  suffix: co0p4_ns25_lay3x5_e10_b10_nr1_fixed_sig0.1_optim
  seed: 20
  ndim: 20
  goal_value: 18
  hidden_list: [5, 5, 5]
  mode: le
  batch_size: 16
  nepochs: 10
  nsamples: 25
  n_init_samples: 50
  init_nepochs: 50
  cut_off: 40
  niter: 41
  lr: 5e-4
  beta: 10
  base_fn: normal
  nr_mix: 1
  only_positive: True
  full_training_last: False
  input_scale: 5.0
  eval_fn: styblinski
  fixed_sigma: 0.1
  problem_type: optim
