alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: styblinski_5d_gacem
  suffix: ns5_lay3x100_e10_b10_nr40_csp_off_fixed_sigma
  seed: 10
  ndim: 5
  goal_value: 5
  hidden_list: [100, 100, 100]
  mode: le
  batch_size: 16
  nepochs: 10
  nsamples: 5
  n_init_samples: 50
  init_nepochs: 50
  cut_off: 50
  niter: 501
  lr: 5e-3
  beta: 10
  base_fn: normal
  nr_mix: 40
  only_positive: True
  full_training_last: True
  input_scale: 5.0
  eval_fn: styblinski
  fixed_sigma: 0.05
  problem_type: csp
  on_policy: False