alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: ackley_2d_gacem
  suffix: co0p4_ns5_lay3x200_e5_b10_nr20
  seed: 10
  ndim: 2
  goal_value: 3.5
  hidden_list: [200, 200, 200]
  mode: le
  batch_size: 16
  nepochs: 5
  nsamples: 5
  n_init_samples: 50
  init_nepochs: 50
  cut_off: 0.4
  niter: 101
  lr: 5e-4
  beta: 10
  base_fn: normal
  nr_mix: 20
  only_positive: True
  full_training_last: False
  input_scale: 5.0
  eval_fn: ackley
  important_sampling: False