alg_class: optnet.alg.autoregressive.ensemble.AutoRegSearch
root_dir: data
params:
  prefix: ens_autoreg
  suffix: styblinski_2d_niter150_s10_b1_nrmix5_lay3
  model_params:
    - hidden_list: [20, 20, 20]
      nr_mix: 5
  seed: 10
  ndim: 2
  goal_value: 20
  mode: le
  batch_size: 16
  nepochs: 5
  nsamples: 5
  n_init_samples: 20
  init_nepochs: 50
  cut_off: 0.4
  niter: 150
  lr: 5e-4
  beta: 1
  base_fn: normal
  full_training_last: False
  input_scale: 5.0
  eval_fn: styblinski
