alg_class: optnet.alg.autoregressive.ensemble_alg.AutoRegSearch
root_dir: data
params:
  prefix: ens_autoreg
  suffix: styblinski_20d_niter1000_s30_b1_nrmix40_lay3x200_e5
#  suffix: styblinski_2d_niter200_s30_b1_nrmix15_lay3_e10
  models:
    - hiddens: [200, 200, 200]
      nr_mix: 40
    - hiddens: [200, 200, 200]
      nr_mix: 40
    - hiddens: [200, 200, 200]
      nr_mix: 40
    - hiddens: [200, 200, 200]
      nr_mix: 40
    - hiddens: [200, 200, 200]
      nr_mix: 40
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
#    - hiddens: [20, 20, 20]
#      nr_mix: 15
  seed: 30
  ndim: 20
  goal_value: 20
  mode: le
  batch_size: 16
  nepochs: 5
  nsamples: 5
  n_init_samples: 20
  init_nepochs: 50
  cut_off: 0.4
  niter: 1000
  lr: 5e-4
  beta: 1
  base_fn: normal
  full_training_last: False
  input_scale: 5.0
  eval_fn: styblinski
