alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: styblinski_15d_gacem
  suffix: co0p4_ns25_lay3x5_e10_b10_nr10_fixed_sig0.1_optim
  seed: 20
  ndim: 15
  goal_value: 20
  hidden_list: [5, 5, 5]
  mode: le
  batch_size: 16
  nepochs: 20
  nsamples: 25
  n_init_samples: 50
  init_nepochs: 0
  cut_off: 40
  niter: 41
  lr: 25e-4
  beta: 10
  base_fn: normal
  nr_mix: 10
  only_positive: True
  full_training_last: True
  input_scale: 5.0
  eval_fn: styblinski
#  fixed_sigma: 0.1
  problem_type: csp
  important_sampling: True
  nepoch_visited: 10
  explore_coeff: 0
  #  visited_fixed_sigma: 0.05
  visited_nr_mix: 20
  allow_repeated: True
