alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: cont_autoreg
  suffix: styblinski_20d_niter1700_s30_b5_nrmix40_lay3
  seed: 30
  ndim: 20
  goal_value: 20
  hidden_list: [200, 200, 200]
  mode: le
  batch_size: 16
  nepochs: 5
  nsamples: 5
  n_init_samples: 20
  init_nepochs: 50
  cut_off: 0.4
  niter: 1700
  lr: 5e-4
  beta: 5
  base_fn: normal
  nr_mix: 40
  only_positive: True
  full_training_last: False
  input_scale: 5.0
  eval_fn: styblinski
