alg_class: optnet.alg.autoregressive.cont_autoreg_optim.AutoRegSearch
root_dir: data
params:
  prefix: levy_20d_gacem
  suffix: co0p4_ns100_lay3x20_e10_b10_nr20_init_hi
  seed: 10
  ndim: 20
  goal_value: 0.4
  hidden_list: [20, 20, 20]
  mode: le
  batch_size: 16
  nepochs: 10
  nsamples: 100
  n_init_samples: 1000
  init_nepochs: 50
  cut_off: 0.6
  niter: 101
  lr: 5e-4
  beta: 10
  base_fn: normal
  nr_mix: 20
  only_positive: True
  full_training_last: False
  input_scale: 10.0
  eval_fn: levy
  important_sampling: False